apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prod-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: developers@fewlines.co
    privateKeySecretRef:
      name: prod-letsencrypt-cluster-issuer
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - dns01:
        route53:
          region: {{ .Values.region }}
          hostedZoneID: {{ .Values.hostedZoneID }}
      selector:
        dnsZones:
        - {{ .Values.rootDnsZone }}
    - http01:
        ingress:
          class: nginx
